spring.application.name=nyfirmasjekk
spring.mvc.problemdetails.enabled=true

# Cache-konfigurasjon
spring.cache.type=caffeine
spring.cache.cache-names=enheter,roller,search,announcements,websiteReachability,websiteContent
spring.cache.caffeine.spec=maximumSize=1000,expireAfterWrite=15m,recordStats

# Actuator & Metrics
management.metrics.tags.application=${spring.application.name}
