CREATE TABLE company_history_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_number VARCHAR(9) NOT NULL,
    name VARCHAR(255) NOT NULL,
    organization_form VARCHAR(255),
    score_color VARCHAR(16) NOT NULL,
    summary VARCHAR(2000),
    municipality VARCHAR(255),
    county VARCHAR(255),
    nace_code VARCHAR(255),
    latest_annual_accounts_year VARCHAR(255),
    vat_registered BOOLEAN,
    registered_in_business_registry BOOLEAN,
    has_contact_data BOOLEAN,
    has_roles BOOLEAN,
    has_serious_signals BOOLEAN,
    registration_date DATE,
    captured_at TIMESTAMP NOT NULL
);

CREATE TABLE company_role_snapshot (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    org_number VARCHAR(9) NOT NULL,
    company_name VARCHAR(255) NOT NULL,
    actor_key VARCHAR(255) NOT NULL,
    actor_name VARCHAR(255) NOT NULL,
    role_type VARCHAR(255) NOT NULL,
    company_score_color VARCHAR(16) NOT NULL,
    active BOOLEAN NOT NULL,
    captured_at TIMESTAMP NOT NULL
);
